### ISSUE TITLE
Fumos are pink again

### ISSUE THREAD

**Issue by realBowl** [The-DoomMan/FumoSkulls#5]
I will wait

**Comment by BlackusPL** [comment]
there is fixed version: https://cdn.discordapp.com/attachments/937428574426763264/1104807704163254492/FumoSkull.dll

**Comment by realBowl** [comment]
thanks

**Comment by nosh62** [comment]
> there is fixed version: https://cdn.discordapp.com/attachments/937428574426763264/1104807704163254492/FumoSkull.dll

Why isn't that version the default?
